// <auto-generated />
using System;
using GasWeb.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GasWeb.Domain.Migrations
{
    [DbContext(typeof(GasWebDbContext))]
    [Migration("20191024102723_AddPriceSubmissions")]
    partial class AddPriceSubmissions
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("GasWeb.Domain.GasStations.Entities.GasStation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("CreatedByUserId");

                    b.Property<DateTime>("LastModified");

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<long>("ModifiedByUserId");

                    b.HasKey("Id");

                    b.ToTable("GasStations");
                });

            modelBuilder.Entity("GasWeb.Domain.PriceSubmissions.Entities.PriceSubmission", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<decimal>("Amount");

                    b.Property<long>("CreatedByUserId");

                    b.Property<int>("FuelType");

                    b.Property<long>("GasStationId");

                    b.Property<DateTime>("LastModified");

                    b.Property<long>("ModifiedByUserId");

                    b.Property<DateTime>("SubmissionDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("PriceSubmissions");
                });

            modelBuilder.Entity("GasWeb.Domain.Users.Entities.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<bool>("Active");

                    b.Property<string>("Name");

                    b.Property<string>("Password");

                    b.Property<int>("Role");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
